project:
  type: website
  preview:
    port: 4200

# author:
#   - name: "Matthew D. Grossi"
#     email: matt.grossi@noaa.gov
#     orcid: 0000-0002-8550-3189
#     git: https://github.com/MattGrossi-NOAA
#     linkedin: https://www.linkedin.com/in/matthewgrossi

format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full
pdf-engine: latexmk
metadata-files:
  - _website.yml
